### ISSUE TITLE
WordPress Jobs

### ISSUE THREAD

**Issue by kjbenk** [aaronjorbin/ama#2]
I am currently in the market for a WordPress Engineering job, mostly customizations and plugin development.  I have applied to a couple of companies already but would you know of any good companies I could apply to or any advice you would have for me?

Thanks :)

Resume: https://gist.github.com/kjbenk/e99438953d617e4b048f
Most Proud of Plugin: https://wordpress.org/plugins/site-audit/
Latest Plugin: https://github.com/kjbenk/get-notified

**Comment by aaronjorbin** [comment]
My path is different than many in the fact that I have never had a stereotypical "WordPress Engineering job". I was always most interested in product development, but interested in selling to the WordPress community. I also have never had much desire to work at an agency.  It just isn't my style. So I've tended to have jobs that used WordPress (but that isn't always the case) rather than jobs that were focused on WordPress. 

Let's step back for a second, what does it mean to be a WordPress Engineer? I personally don't want to work with people that paint themselves into the corner of just knowing WordPress. I like T-shaped people. Have you worked on things other than WordPress?  Your resume doesn't list much else technical. Are you most comfortable in PHP, JavaScript, or something else?  Have you done much (or any) systems/server work?   Resumes are about helping you prepare the interviewer to ask you good questions.

When finding jobs (and deciding between jobs), The question I often asked is "How will this prepare me for the job I want after it?".  Make sure that the position is going to help you become qualified for a job you want that you aren't qualified yet.

I also have a multiple question test for evaluating companies that I'll be publishing next week. This of it as a WordPress version of the [Joel Test](http://www.joelonsoftware.com/articles/fog0000000043.html). 

Some of the specific places I would recommend making sure you check out include [Human Made](https://hmn.md/is/hiring/), [iThemes](https://ithemes.com/jobs/), and [pagely](https://pagely.com/careers/).  Also, since you are in the Philly area, I have to mention [Yikes](http://www.yikesinc.com/).  

I hope that helps.

**Comment by kjbenk** [comment]
Thanks so much for the detailed reply I really appreciate it :)

What do you mean by:

> I like T-shaped people.

**Comment by aaronjorbin** [comment]
It refers to people with a wide base that have the ability to collaborate across disciplines while having something they can own as a specialty.  

For example: even if you are primarily a backend developer, being able to give quality design feedback, participate in product brainstorms, setup servers, and build functional UIs while also completing owning database transactions.  

Some articles worth reading:

[IDEO CEO Tim Brown: T-Shaped Stars: The Backbone of IDEO’s Collaborative Culture](http://chiefexecutive.net/ideo-ceo-tim-brown-t-shaped-stars-the-backbone-of-ideoae%E2%84%A2s-collaborative-culture/)
[Why engineers need to develop T-Shaped Skills](http://blogs.ptc.com/2014/12/03/why-engineers-need-to-develop-t-shaped-skills/)
